# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FlatLoss": "losses.ipynb",
         "FlatCrossEntropyLoss": "losses.ipynb",
         "FlatBCELoss": "losses.ipynb",
         "FlatMSELoss": "losses.ipynb",
         "recall_at_k": "metrics.ipynb",
         "precision_at_k": "metrics.ipynb",
         "SimpleCF": "networks.ipynb",
         "StepBase": "step.ipynb",
         "Step": "step.ipynb",
         "moving_avg": "utils.ipynb"}

modules = ["losses.py",
           "metrics.py",
           "networks.py",
           "step.py",
           "utils.py"]

doc_url = "https://dpoulopoulos.github.io/cf_step/"

git_url = "https://github.com/dpoulopoulos/cf_step/tree/master/"

def custom_doc_links(name): return None
