# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SimpleCF": "networks.ipynb"}

modules = ["networks.py"]

doc_url = "https://dpoulopoulos.github.io/cf_step/"

git_url = "https://github.com/dpoulopoulos/cf_step/tree/master/"

def custom_doc_links(name): return None
