# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/networks.ipynb (unless otherwise specified).

__all__ = ['SimpleCF']

# Cell
import torch.nn as nn

from torch import tensor

# Cell
class SimpleCF(nn.Module):
    def __init__(self, n_users, n_items, factors):
        super().__init__()
        self.user_embeddings = nn.Embedding(n_users, factors)
        self.user_embeddings.weight.data.normal_(0., .1)
        self.item_embeddings = nn.Embedding(n_items, factors)
        self.item_embeddings.weight.data.normal_(0., .1)

    def forward(self, u, i):
        user_embedding = self.user_embeddings(u)
        item_embedding = self.item_embeddings(i)
        rating = user_embedding @ item_embedding
        return rating